ruta_corpus: datos/corpus.txt
directorio_respaldos: respaldos
motor_computo: pytorch
estrategia_tokenizacion: palabra
token_desconocido: <UNK>
criterio_seleccion_vocabulario: porcentaje
cantidad_palabras_unicas: 15000
porcentaje_palabras_unicas: 1.0
frecuencia_minima: 1
muestreo_negativo: false
cantidad_muestras_negativas: 5
tamanio_ventana: 4
dimension_embedding: 100
tasa_aprendizaje: 0.2
cantidad_epocas: 1000
hacer_respaldo: true
frecuencia_respaldo: 100
tamanio_lote: 2048
semilla_aleatoria: 26
reanudar_entrenamiento: false
ruta_checkpoint: respaldos/modelo_cbow_w4_epoca_1000.npz
